hash-format = "sha256"

[[files]]
file = "1_20.jar"
hash = "ff41c542cec182ce74508a5e42194e0f4009341de75f0a7bf770d18cf701d56b"

[[files]]
file = "index.html"
hash = "6d19bfd4d8659d6013bdcfbbc7105d660abfc5e2f643cc060184fd642fd33e68"

[[files]]
file = "mods/fastload-fabric-url.pw.toml"
hash = "de975cee9fd5f1220352fa3fe8c0b92d37e5ed1e35f0bb9cb35702504938e048"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "b5a80beb6c7d1ea261fdfc4d2c4f31377f630381d43fd2caa6edf9e5d46c0173"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6c681a60f617657bb819dae03d180a92a513908705518480391dfd55783b457a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "97ffbc7d0e4087777c5e3732780f01958f99d44c4f09fd534bbb8f239d4980a1"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "21e92010a664ed7c9f4b9d84e48b2e85903dd28049dbebbeb52aad03942f159a"
metafile = true

[[files]]
file = "mods/raknetify.pw.toml"
hash = "5f45c21d5909383abd26551620a6bfa35dcf264e1ec5a3121b08596d9924cbbc"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "7a8d5e151619f34a346e505a601bb1d0f86c4f371aac533c50d9792c6d63a363"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "77fb235736e2876ad3329aaf377b57f367808988d01ef661caf338b5817a431e"
metafile = true
